### ISSUE TITLE
Student task list mobile view schedule definition entries completion not updating

### ISSUE THREAD

**Issue by MaximStockmans** [SELab-2/Dr-Trottoir-3#262]
@pipieter found that the amount of completed buildings in a schedule definition did not get updated in the student task list mobile view.

**Comment by pipieter** [comment]
The issue is caused in StudentTaskListComponent.tsx on lines 79 and 85. These lines use a map and filter respectively, but the element is both times named 'e', causing name shadowing.

One small additional issue is that line 85 does not check for duplicates, while the system (and client) do allow for there to be multiple schedule work entries of the same type, for the same building and date.
